export default {
    "sample": [
    {
        "qs": "Many people believe that social networking sites (such as Facebook) have had a huge negative impact on both individuals and society.  To what extent do you agree?",
        "answer": "Social networking sites, for instance Facebook, are thought by some to have had a detrimental effect on individual people as well as society and local communities. However, while I believe that such sites are mainly beneficial to the individual, I agree that they have had a damaging effect on local communities.  With regards to individuals, the impact that online social media has had on each individual person has clear advantages. Firstly, people from different countries are brought together through such sites as Facebook whereas before the development of technology and social networking sites, people rarely had the chance to meet or communicate with anyone outside of their immediate circle or community. Secondly, Facebook also has social groups which offer individuals a chance to meet and participate in discussions with people who share common interests.  On the other hand, the effect that Facebook and other social networking sites have had on societies and local communities can only be seen as negative. Rather than individual people taking part in their local community, they are instead choosing to take more interest in people online. Consequently, the people within local communities are no longer forming close or supportive relationships. Furthermore, society as a whole is becoming increasingly disjointed and fragmented as people spend more time online with people they have never met face to face and who they are unlikely to ever meet in the future.  To conclude, although social networking sites have brought individuals closer together, they have not had the same effect on society or local communities. Local communities should do more to try and involve local people in local activities  in order to promote the future of community life."
    },
    {
        "qs": "Some people think that the teenage years are the happiest times of most people's lives. Others think that adult life brings more happiness, in spite of greater responsibilities.  Discuss both these views and give your own opinion.",
        "answer": "What's the happiest time in people's lives: youth or old age; school, career or retirement? All of these have been suggested, but teenage years and adulthood both have many supporters.  Those who believe teenagers are the happiest people cite their lack of responsibilities as a significant factor. They are supported financially and emotionally by their parents, and although they may be included in family decisions, they're not ultimately responsible. However, adolescents are on the threshold of adult life: they're old enough to get a part-time job, so they can enjoy their first taste of financial independence, and their future study and career lie ahead.  Away from these serious concerns, young people have an active social life with their friends, often simply by hanging out with them. And of course, there’s the excitement of first love and first heartbreak. With all this to experience, teenagers see their parents' lives as boring and stressful.  However, the reverse is also true. Adults see anxious, self-dramatising adolescents, and appreciate the joys of maturity. These may include a contented family life, long-lasting friendships and a career. Long-term relationships may not have the fireworks of adolescence, but are stronger for it, because of the wealth of shared experience. At work, many of us are challenged and stimulated by the increasing, professional skills we acquire, which ensures that our jobs remain interesting.  The greatest benefit, though, is that maturity gives you greater confidence in your own judgement, in all areas of life. You’re not afraid to express your opinion when others disagree and, unlike a teenager, you know when to let things go.  Both these periods can be happy times, but I look back at my own teenage years, with no desire to go back. Adult life may be less dramatic, but fireworks don’t keep you warm"
    },
    {
        "qs": "In cities and towns all over the world the high volume of traffic is a problem.  What are the causes of this and what actions can be taken to solve this problem?",
        "answer": "It is undoubtedly the case that urban areas around the world increasingly suffer from congestion. In this essay, I examine the reasons for this trend and suggest some practical policies the authorities could implement to reduce the level of traffic in our cities.  The first step is to understand why traffic has increased in towns and cities. Broadly speaking, there are three main reasons for this. One is that cars have become more affordable for the average consumer and they are no longer a luxury item, but something that most families expect to own. A second reason is that public transport has become increasingly unreliable in recent years, not least because many bus and train services have been reduced because of the difficulty in funding them. The third reason is that society has in general become more mobile and this means more people are prepared to commute to work by car than they were before.  There is almost certainly no one solution to this problem given the complexity of its causes. However, one option has to be to improve the reliability of public transport to encourage people to take the bus or the train rather than get in the car. It would also be possible to discourage people from driving to work by introducing special tariffs for using the roads, especially during peak periods. A successful example of this is the congestion charge scheme in London which has certainly reduced the level of trafficin inner-city areas.  In conclusion, there are a variety of different factors that have led to rising levels of traffic in urban areas. While it may not be possible to find a complete solution, any action should probably involve encouraging greater use of public transport and making it more expensive for the motorist to drive in urban areas."
    }
]
}
